### ISSUE TITLE
Toggle button for Style Editor side panels doesn't work

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#451]
The side panel toggle button doesn't work within the *Style Editor* panel.
![Side panels toggle button in *Style Editor* panel](https://cloud.githubusercontent.com/assets/958943/11235233/f674657c-8dcf-11e5-8f00-124db8c27062.png)

Sebastian

**Comment by janodvarko** [comment]
Fixed by https://github.com/firebug/firebug.sdk/commit/8b148af714e18623f9e47230e3d7707f5e971b89

You need git pull from firebug.sdk repo.

Honza

**Comment by darkred** [comment]
> You need git pull from firebug.sdk repo.

Sorry to bother you, but what do you mean? How to do the `git pull`?

What I have done so far:

Initially
```
git clone https://github.com/mozilla/jpm
cd jpm
npm install 
npm link
cd ..
git clone https://github.com/firebug/firebug.next
cd firebug.next
npm install
```
Today:
```
cd firebug.next
npm update
jpm xpi
```
and the produced xpi didn't contain the mentioned fix.

I also tried today:

```
cd ..
git clone https://github.com/firebug/firebug.sdk
cd firebug.sdk
npm install
cd ../firebug.next
npm update
jpm xpi
```
but there was the same state with the produced xpi.

**Comment by janodvarko** [comment]
Yeah it's because I am not publishing Firebug.sdk after every commit. I am rather having linked the firebug.sdk directory using: npm link (just like you did for jpm above).

So, git pull origin master from firebug.sdk directory is actually enough

@darkred Does that make sense?

Honza

**Comment by darkred** [comment]
@janodvarko Alright. 
So, I did a `git pull origin master` (and `npm link` ) in firebug.sdk directory.
But, the generated xpi (via `git pull`,`npm update`,`jpm xpi` in firebug.next directory) 
still doesn't contain the mentioned fix (I just tested it in a clean Nightly 45 x64 profile).
Could you please take a look? 
https://www.dropbox.com/s/vmm19chwlcnxf4r/firebug%40software.joehewitt.com-3.0.0-beta.1.xpi?dl=0
(804 KB)

**Comment by janodvarko** [comment]
@darkred
Package linking is two steps process.

1) npm link // in firebug.sdk
2) npm link firebug.sdk // in firebug.next

See more:
https://docs.npmjs.com/cli/link

To make sure that you setup that correctly check out the node_modules/frebug.sdk (in firebug.next dir) it should be slink not a dir.

Does it help?

Honza

**Comment by darkred** [comment]
Yes, by uninstalling both, and then first `npm cache clean` and then installing them again, and it's ok now!! Thanks a lot for your help, once more!
_One thing to notice: the xpi now is 1026 KB instead of 804._ 

***


And something more:

I use Firefox nighly/inbounds exclusively, and as a javascript hobbyist it's great been able to watch the development of (and use) firebug.next each day, and even contribute to it if I can. 
*(But, this was the first time for me to build an xpi, i.e. trying with git,npm,jpm,etc. That's why I needed help a few times to clarify things).*

So I'd like to make this suggestion, please:
to update the info on how to build firebug.next (to both the project's [main page](https://github.com/firebug/firebug.next) and the [wik](https://github.com/firebug/firebug.next/wiki)i ) 
with the above info - especially about the installation of firebug.sdk that's required -. 
It would be very useful for anyone (like myself) who wants to build the latest xpi, each day.

**Comment by janodvarko** [comment]
>  and it's ok now. Thanks a lot for your help, once more! I really appreciate it.

Excellent!

> firebug.next each day, and contribute to it if I can.
Sounds great!
 
> So I'd like to make this suggestion, please:

Good point I'll do it.

Honza

**Comment by darkred** [comment]
> Good point I'll do it.
Thank you.

I just installed Firebug 3 beta 2 in Nightly x64 2015-11-20 (even on a clean profile),
and the Media Rules toggle button is not working.

*Also, another thing I noticed is that, the latest xpi I built via `jpm xpi` was 1034 KB
while, the one for beta 2 is 801 KB*

**Comment by SebastianZ** [comment]
Just for confirmation, it's also working for me now. Thank you, Honza!

Sebastian

**Comment by darkred** [comment]
[**@SebastianZ**](https://github.com/SebastianZ) commented on [Nov 23, 2015, 1:42 PM GMT+2](https://github.com/firebug/firebug.next/issues/451#issuecomment-158912009 "2015-11-23T11:42:05Z - Replied by Github Comment Enhancer"):
> Just for confirmation, it's also working for me now. Thank you, Honza!
> 
> Sebastian

I just tried installing it once more in Nightly 45.0a1 x64 2015-11-22 (win 10 x64) in a clean profile (with e10s enabled),
and the toggle button is not working!

Also, the button doesn't work after 
either rightclicking on the tab and pressing "Open in a new non-e10s window"
or after disabling e10s via Options|General|untick "Enable multiprocess Nightly" (and restart).

**Comment by SebastianZ** [comment]
> I just tried installing it once more in Nightly 45.0a1 x64 2015-11-22 (win 10 x64) in a clean profile (with 
> e10s enabled), and the toggle button is not working!

Right, it just works when running `jpm run` or building my own XPI. The changes done in this issue are not included in Firebug 3 beta 2. Honza, why's that?

Sebastian

**Comment by darkred** [comment]
@janodvarko A comment on this, please?

**Comment by janodvarko** [comment]
Ah, both should be fixed now:
https://github.com/firebug/firebug.next/releases/tag/firebug-3.0.0-beta.3

- The Firebug.sdk module wasn't updated. I forgot `npm pull` when doing the release :-)
- The xpi size is smaller (only firebug.sdk is included now)

Honza

**Comment by darkred** [comment]
Thank you
